### ISSUE TITLE
How can I implement an on-change event on jodit-vue

### ISSUE THREAD

**Issue by Ronak-maker** [WendellAdriel/jodit-vue#19]
hey, @WendellAdriel 
I want a trigger event when jodit-vue is started editing, but I don't know how can I apply an on-change event on "jodit-vue" package.
I tried the following ways. but it didn't work.

`<jodit-editor v-model="product_info_text_desc"  :config="fire(this.element, 'change')" />`
`<jodit-editor v-model="product_info_text_desc"  @change="startEditing"/>`
`<jodit-editor v-model="product_info_text_desc"  v-on:change="startEditing"/>`

please help.

**Comment by WendellAdriel** [comment]
Hello @Ronak-maker.
I think I understood what you need and I can think on some ways.
It would be better to have a working example for me to check, but did you try setting up a `watcher` for the model of the editor?

**TEMPLATE**
```html
<jodit-editor v-model="myText" />
```

**WATCHER**
```js
export default {
  // YOUR CODE HERE...
  watch: {
    myText(newValue) {
      // TRIGGER EVENT
    }
  }
}
```

**Comment by Ronak-maker** [comment]
Hey, @WendellAdriel 
Thanks for the reply.

I am updating `myText` on page load and page refresh. so, whenever the page is load and refresh, the change event is fire. I need to change event fire when the user actually enters text in the textbox.

**Comment by WendellAdriel** [comment]
Ok @Ronak-maker, so even with the fire from the editor itself you'll have an issue with this.
The `myText` is a `data`, `computed`, `props`?

Because what I can think of is when you initialize your component, on the `created` lifecycle, you can create a "backup variable" that will host the `myText` and when you set a watcher for `myText` you compare this with the "backup variable" and if the content is different, then you execute your code and if the content is the same, you just ignore it.

Just note that this "backup variable" cannot be reactive/linked with the original `myText`, this variable needs to be set up once and changed only on the `created` lifecycle for this to work.

**Comment by WendellAdriel** [comment]
@Ronak-maker I saw that you closed the issue, but did you find a solution for your problem?

**Comment by Ronak-maker** [comment]
Hello @WendellAdriel ,
I could not find a solution from the jodit event. Then I used the on-change event of the textbox with the help of javascript.

**Comment by bcreation** [comment]
@Ronak-maker I found the event name. 
` <jodit-editor ref="jodit" v-model="content" :config="config" @input="updateContent" />`
