### ISSUE TITLE
Destruct method

### ISSUE THREAD

**Issue by daarxwalker** [WendellAdriel/jodit-vue#2]
Before my issue, great job man!
But...There's no destroy method, which need, when switching textarea and wysiwyg. I create my own Jodit Vue component, and used destruct method ( this.editor.destruct() ) in beforeDestroy() Vue cycle.
I think, it's good idea to add it.

**Comment by WendellAdriel** [comment]
Oh man, I totally forgot about that!!!
Thank you so much for remembering me, I'll do that today yet, right now I'm finishing some things at my company, but I'll make a release today with that!!! 😉

**Comment by daarxwalker** [comment]
No problem, official docs are deprecated, cs destroy() no longer exists in new version, replaced by destruct(). Some Googling and reading source code -.- :D

**Comment by WendellAdriel** [comment]
Sorry for taking this long to solve this issue @daarxwalker .
I was very busy with company tasks and home tasks because of the holidays.
But this is already ok on https://github.com/WendellAdriel/jodit-vue/releases/tag/v1.2.2

Thanks for the help!!!
And since the project follows the All Contributors guide, I added your user on the contributors list!!!
😉
