### ISSUE TITLE
Support Content Security Policy (CSP)

### ISSUE THREAD

**Issue by Qolzam** [WendellAdriel/jodit-vue#44]
Currently jodit is adding some inline-style which cause issue for CSP. Do we have anyway to solve this issue?

**Comment by WendellAdriel** [comment]
Is this specific for the wrapper?
If this is a general Jodit issue I'll recommend that you create this directly in Jodit repository: https://github.com/xdan/jodit

**Comment by Qolzam** [comment]
Thank you for reply @WendellAdriel 🙂,

No this it not an issue for the wrapper but I thought you may have a solution to solve this issue. 
In this case let me close this issue!
Thanks again🙏🏼

**Comment by WendellAdriel** [comment]
@Qolzam I did a small check but since those styles are added by the Jodit editor code itself, trying to do something in the wrapper could lead to several issues, so I prefer that these kinds of problems are tackled in the Jodit Editor code itself!
I'm happy to help and I encourage you to check if this is already being tackled in the Jodit Editor or to create an issue there for that! 😉
